# Project information
site_name: AD域控与数据通信网络
site_url: https://hoochanlon.github.io/aitii-tekisuto
site_author: Martin Donath
site_description: >-
  本文档覆盖了AD域控与数通的架构设计、部署实施、安全加固与日常运维。

# Repository
repo_name: hoochanlon/aitii-tekisuto
repo_url: https://github.com/hoochanlon/aitii-tekisuto

# Copyright
copyright: Copyright &copy; 2020 - 2099 Hoochanlon

# Configuration
theme:
  name: material
  custom_dir: material/overrides
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Plugins
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: false
  - mermaid2:
      version: 10.0.2

# Hooks
hooks:
  - material/overrides/hooks/shortcodes.py
  - material/overrides/hooks/translations.py
  - material/overrides/hooks/encrypt.py

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hoochanlon
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/hoochanlon.bsky.social
    - icon: fontawesome/brands/twitter
      link: https://hoochanlon.github.io/twitter

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

not_in_nav: |
  /tutorials/**/*.md

# Page tree
nav:
  - Home: index.md
  - AD域控:
    - 活动目录: ad/index.md
    - 主干体系:
      - 一、安装域控: ad/1-ad-anzhuang-yukong.md
      - 二、磁盘分区管理: ad/2-ad-cipan-guanli.md
      - 三、R430 服务器组硬件 RAID: ad/3-ad-r430-raid.md
      - 四、安装 WSUS: ad/4-anzhuang_wsus.md
      - 五、添加电脑到域测试组策略效果: ad/5-yu-ruanjian-xianzhi.md
      - 六、使用组策略部署软件: ad/6-yu-ruanjian-anzhuang.md
      - 七、添加备份域控制器实现容错: ad/7-beifen-yukong.md
      - 八、将域控迁移到新买的服务器: ad/8-huanxin-yukong.md
      - 九、域控及文件服务器迁移方案: ad/9-qianyi-yukong-fang-an.md
    - 枝叶细节:
      - 十、 H3C INode 上网许可与域控创建用户及文件夹授权: ad/10-inode-and-domain-access-manager.md
      - 十一、域控组织组织单元人员迁移: ad/11-domain-organization-unit-member-migration.md
      - 十二、删除用户共享文件夹权限: ad/12-delete-user-shared-folder-permission.md
      - 十三、批量添加、删除域用户及导出: ad/13-batch-add-delete-domain-user-and-export.md
      - 十四、组织单元与域用户还原: ad/14-domain-organization-unit-and-user-restoration.md
      - 十五、批量对人员进行文件夹授权: ad/15-batch-add-permission-to-users-folder.md
      - 十六、文件夹安全权限转换对应共享权限: ad/16-file-folder-security-permission-conversion-corresponding-shared-permission.md
      - 十七、组策略常用软件下发，以及统一域用户壁纸: ad/17-group-policy-common-software-distribution-and-uniform-domain-user-wallpaper.md
    - 域控脚本:
      - Powershell介绍: ad/scripts-desc/index.md
      - 一、一键切换Windows系统版本与激活Windows及Office: ad/scripts-desc/1-win-offce-active.md
      - 二、快捷修改IP与软件安装自动化: ad/scripts-desc/2-ip-config-and-soft-install.md
      - 三、根据文本 批量添加相关权限: ad/scripts-desc/3-add-permission-by-text.md
      - 四、查看用户相关文件夹权限，以及移除权限: ad/scripts-desc/4-remove-permission.md
      - 五、域用户人员增删、文件授权、组织单元与域用户恢复: ad/scripts-desc/5-aduser-and-permission-management.md
      - 六、域用户导出到txt文件汇总: ad/scripts-desc/6-aduser-export-to-txt.md
      - 七、Windows基线检查脚本: ad/scripts-desc/7-windows-baseline-script.md
  - 数据通信:
    - Datacom: datacom/index.md
    - 电话网络:
      - 一、办公室电话接入部署: datacom/phone/1-office-phone-access-deployment.md
      - 二、溯源电话运作原理: datacom/phone/2-phone-operation-principle.md
    - 电脑网络:
      - 一、OA办公网络接入层运营: datacom/pc/1-oa-office-network-access-layer-operation.md
      - 二、 网络设备组装发展过程略: datacom/pc/2-network-device-assembly-development-process.md
      - 三、一篇全文让你彻底理清IP地址、子网掩码、网关: datacom/pc/3-ip-address-subnet-mask-gateway.md
    - 设备网络:
      - 一、主备堆叠三层网络总体理论: datacom/device/1-master-standby-stack-three-layer-network-theory.md
      - 二、主备堆叠三层网络速成理解: datacom/device/2-master-standby-stack-three-layer-network-fast-track.md
      - 三、网络配置删减规则: datacom/device/3-network-configuration-reduction-rules.md
    - 网络设备配置备份:
      - 一、交换机配置备份: datacom/backup/1-switch-configuration-backup.md
      - 二、防火墙配置备份: datacom/backup/2-firewall-configuration-backup.md
    - 故障排除:
      - 一、一次因AD服务器断电导致的认证故障分析: datacom/troubleshooting/1-ad-server-power-off-authentication-failure-analysis.md
      - 二、一次网络环路事故：当“部分不通”演变为全网瘫痪: datacom/troubleshooting/2-network-loop-accident.md
      - 三、企业环境中代理上网异常的系统化排查与根因分析: datacom/troubleshooting/3-proxy-connectivity-troubleshooting-rca.md
      - 四、关于加密沙盒环境下网页访问异常的排查分析与技术报告: datacom/troubleshooting/4-encrypted-sandbox-environment-web-access-abnormal-troubleshooting-and-technical-report.md
      - 五、简明网络故障排查思路: datacom/troubleshooting/5-simple-network-fault-diagnosis-thinking.md
  - 信息安全:
    - 信息安全: security/index.md
    - 一、利用“永恒之蓝”漏洞的挖矿蠕虫在隔离网络中的传播与处置: security/1-eternal-blue.md
    - 二、Synaptics病毒事件分析: security/2-synaptics-virus-event-analysis.md
    - 三、云主机安全攻防实战：从暴力破解、挖矿木马到纵深防御体系的构建: security/3-dont-let-your-cloud-server-become-a-hackers-puppet.md
    - 四、防火墙邮件拦截: security/4-firewall-email-interception.md
    - 五、“银狐”木马借钉钉通讯群进行社会工程学攻击的事件报告: security/5-silver-fox-social-engineering-attack-report.md
    - X、【特别篇】机房巡检工作与UPS应急演练: security/x-special-chapter-room-inspection-and-ups-emergency-drill.md
  - 文案写作:
    - 文案写作: outline-the-docs-scheme/intro-template/index.md
    - 一、驻点工程师岗位工作手册: outline-the-docs-scheme/intro-template/1-job-manual-of-on-site-engineer.md
    - 二、驻场IT运维服务季度报告: outline-the-docs-scheme/intro-template/2-IT-onsite-support-service-quarterly-report-2020Q3.md
    - 三、IT运维项目服务（投标）: outline-the-docs-scheme/intro-template/3-IT-onsite-support-service-bidding-book.md
    - 预案模板参考:
      - 一、业务持续性计划预案 - 服务器故障预案: outline-the-docs-scheme/plan-template/1-business-continuity-plan-server-failure-plan.md
      - 二、业务持续性计划预案 - UPS应急演练方案: outline-the-docs-scheme/plan-template/2-business-continuity-plan-ups-emergency-drill-plan.md
      - 三、业务持续性计划预案 - 网络故障应急方案: outline-the-docs-scheme/plan-template/3-business-continuity-plan-network-failure-emergency-plan.md
      - 四、业务持续性计划预案 - 网络设备故障应急方案: outline-the-docs-scheme/plan-template/4-business-continuity-plan-network-device-failure-emergency-plan.md
      - 五、业务持续性计划预案 - 专线故障预案: outline-the-docs-scheme/plan-template/5-business-continuity-plan-dedicated-line-failure-plan.md
    - 整改模板参考:
      - 一、信息安全监控整改报告: outline-the-docs-scheme/rectify-template/1-information-security-monitoring-rectification-report.md
      - 二、监控专线故障报告: outline-the-docs-scheme/rectify-template/2-monitoring-dedicated-line-failure-report.md
      - 三、xxxx故障整改报告: outline-the-docs-scheme/rectify-template/3-xxxx-failure-rectification-report.md
    - 演练模版参考:
      - 一、UPS切换演练结果报告: outline-the-docs-scheme/drill-template/1-ups-switch-drill-result-report.md
      - 二、网络设备与专线应急演练报告: outline-the-docs-scheme/drill-template/2-network-device-and-dedicated-line-emergency-drill-report.md
    # - 项目文档参考:
    #   - 一、XX项目机房与职场搬迁计划: outline-the-docs-scheme/project-template/1-xx-project-data-center-and-office-move-plan.md

    - 邮件汇报模板参考:
      - 内部开展XX工作会议通知: outline-the-docs-scheme/email-template/1-internal-XX-meeting-notification.md
      - 关于补充采购办公电脑及相关授权的申请: outline-the-docs-scheme/email-template/2-application-for-additional-purchase-of-office-computers-and-related-authorizations.md
      - 【加班申请】关于x月x日xx项目配合甲方开展xx项目演练的加班申请: outline-the-docs-scheme/email-template/3-application-for-overtime-work-due-to-xx-project-xx-project-drill.md
      - 有关XX撤场设备处置事项申请: outline-the-docs-scheme/email-template/4-application-for-the-disposal-of-xx-project-equipment-due-to-xx-project-termination.md
      - 关于XX运营商专线故障处理情况的报备: outline-the-docs-scheme/email-template/5-report-on-the-processing-of-xx-operator-dedicated-line-failure.md
      - 【专线割接报备】XX运营商专线割接: outline-the-docs-scheme/email-template/6-dedicated-line-cutover-report.md
      - 【专线测试报备】XX备线专线参数测试: outline-the-docs-scheme/email-template/7-dedicated-line-parameter-test-report.md
  - 办公协同:
    - 新人办公基础设备使用入门: office-knowledge-base/new-employee-office-basic-equipment-usage-manual.md
    - 测试文章: office-knowledge-base/test.md
  - Demo:
    - Demo: demo/index.md
    - 文章加密: demo/encrypt.md
  - Blog: https://hoochanlon.moe
